### ISSUE TITLE
Create assignment and assign IPE rubrics in each course

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#11]
Parent Issue: https://github.com/tl-its-umich-edu/IPE-competencies-updater/issues/7

This issue is 1/3 of [Parent issue](https://github.com/tl-its-umich-edu/IPE-competencies-updater/issues/7) creating an assignment in each IPE course, if an assignment already exist then delete only the IPE assignment and create the assignment in the same group. If multiple IPE assignment group exist then delete all the assignments in all the assignment group and can create assignment to any group.

**Basically, this issues is wiring this portion of flowchart**

![Screen Shot 2021-11-09 at 9 00 21 AM](https://user-images.githubusercontent.com/8579775/140937596-c908b0b7-5028-46ff-b21b-b6e48a7062ce.png)

The deletion of assignment in a IPE course is an edge case, since these assignments are only created by script and no instructor will do this. In case of copied courses this might be a unneeded IPE assignment in course  so we are supporting this case. 

below are the strings to look for
```
ASSIGNMENT_NAME = 'IPE Competencies Attained'
ASSIGNMENT_GROUP_NAME ='IPE Competencies'
```

```
If assignment_group_exist and assignment_exist :
   delete/create assignment in same group
if (assignment_group_doesn't_exist):
  create assignment/and group
if (multiple_Assignment_groups_exist):
  delete all assignment
  create assignment in any group
```
------------------------------------------------------
Test plan:

Go to a course in canvas and see only one IPE assignment is created in IPE group and rubric is assigned. Repeat for multiple courses

**Comment by jennlove-um** [comment]
Testing passes. When a pre-existing assignment called IPE Competencies Assigned is found in a course, the script deletes the existing assignment and creates a new one with the data from the spreadsheet.
