### ISSUE TITLE
Modify the Rubric response for simplicity when assigning a particular competency

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#13]
Parent issue #7 

This issue is 2/3 of [Parent issue](https://github.com/tl-its-umich-edu/IPE-competencies-updater/issues/7) getting Rubric and simplifying the Rubrics data. In the flow diagram it is the purple circle.

![Screen Shot 2021-11-09 at 11 21 06 AM](https://user-images.githubusercontent.com/8579775/140964504-cadd52d6-3bca-41a4-874d-02a2d551a1dc.png)

The Rubric for IPE is going to be constant and will be residing in IPE subaccount always. Once Rubrics is assigned to students it cannot be changed. So we can configure these as environmental variable if we had to use a new one for what ever reasons
The IPE Rubric: https://canvas-test.it.umich.edu/accounts/1245/rubrics/76864

I have written tests Rubric data returned as expected. I haven't written the IF Rubric API call is success or not as I already did a general purpose testing API response `api_handler_test.py`

**Comment by jennlove-um** [comment]
Testing passes.  The rubric specified in the configuration is used for assigning competencies by the script.
