### ISSUE TITLE
assign competencies to student based on the criteria by course design

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#14]
Parent issue #7 
This issue deals with assigning competencies to students in the course. 
1. Only active student enrollments are gathered
2. based on the criteria assigned for a course in the google spreadsheet,[All Enrolled or > 70% grade], students will receive competencies
3.  final_score is consider for competency assignment

Tests are written testing most of the scenarios. 
It's is taking about 2 min to assign competencies for ~200 students in the course

![Screen Shot 2021-11-18 at 3 56 14 PM](https://user-images.githubusercontent.com/8579775/142495398-f705e2be-2c3e-4ca2-96fe-2aa07158fc33.png)

Logging format for assigning competencies
Success Case
```
INFO: For course 448447 with competencies criteria: `Passing - 70% or Higher`, 5/5 students will receive competencies
INFO: 5/5 Students assigned competencies in course 448447 in assignment 448447122
```
Few Failure case
```
INFO: For course 448447 with competencies criteria: `All Enrolled`, 10 students will receive competencies 
ERROR: 7/10 Students didn't got competancies assigned in course 448447 in assignment 448447122 to the following students [{136950: 'Student User6'}, {136951: 'Student User7'}, {136953: 'Student User9'}]
```

**Comment by jennlove-um** [comment]
Testing passes.  Competencies are correctly assigned to students based on the criteria for assigning.
