### ISSUE TITLE
 Read the IPE course offerings from the Google sheets

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#2]
This issue is research how to read and write the google sheet and have the basic wiring for reading sheets data.

[gspread](https://docs.gspread.org/en/latest/) library is used, as this is a simple wrapper for Google sheets API. The IPE process needs reading and updating the google spreadsheet. Update the Column `Script Run?` to say that those marked courses script is run and next time the scripting process continue with other courses.

**Comment by jennlove-um** [comment]
Testing passes - data from the specified Google Sheet is used to assign competencies to students in courses.
