### ISSUE TITLE
Filter duplicate student entries as part of multiple section enrollments in the course

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#23]
When students are enrolled in multiple sections when fetching the `/enrollments` data they will have 2 enrollments id's with same grade data. So the fix would be filter the duplicate data. Use[ course 414909](https://canvas-test.it.umich.edu/courses/414909) as reference as this bug was found there

**Comment by jennlove-um** [comment]
Testing passes - students with enrollments in multiple sections are correctly assigned competencies based on competency criteria.
