### ISSUE TITLE
Update the log message for hard concluded courses which doesn't have active enrollments

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#25]
In case of Concluded courses, the canvas course will have a workflow_state = completed. 
Once the competencies process run for these type of courses, the worksheet get updated as well. Changing the log statement would help for this scenario. Below is the suggested message.

`0 active enrolled students may receive IPE competencies in the course 11111. 0 students received competencies.`

Course to test 332108

**Comment by pushyamig** [comment]
@jennlove-um, Suggest the log message if things are still not clear.

**Comment by jennlove-um** [comment]
Testing passes for concluded courses.  The log shows the correct message.
