### ISSUE TITLE
Filter courses based on the right values of dosage, competencies, and criteria for assigning LO

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#26]
After fetching the courses based on the on `When does script run? (Feb, June, Oct)` and `Script Run?` below rule is be applied in removing the IPE offering for picking which courses to run

1. `Course id` should be a number
2. `Dosage` should a integer and in range 0, 100
3. `5 competencie`s should only have value of `[Practice, Reinforce, Introduce, N/A]`
4. `Criteria for assigning LO` should only be `Passing - 70% or Higher` or `All Enrolled`
5. Duplicate rows with any of the above columns will be dropped.

**Comment by jennlove-um** [comment]
1. Course ID null or text correctly filters out the row.
2. Dosage null, text, or outside the range 0-100 correctly filters out the row.
3. Competencies with valid values correctly update.  Invalid values correctly filters out rows.
4. Criteria Passing - 70% or Higher and All Enrolled correctly assign competencies. Do Not Run, null, and invalid entries correctly filter out rows.
5. Duplicate rows with any mismatched columns in dosage, competencies, or criteria correctly filter out rows.
