### ISSUE TITLE
Improve the google service account path for running the script

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#6]
Remove the IS_DOCKER_RUN variable and instead have the absolute path to the google service account file. this way support running in docker or command line( this is convenient)

For Docker run set this
`GSERVICE_ACCOUNT_PATH=/secrets/ipe/ipe_gserviceaccount.json`
For Running via command line
`GSERVICE_ACCOUNT_PATH=/user/home_directory/secrets/ipe/ipe_gserviceaccount.json
`

----------------------------------------------------------------------
Could probably create this as an issue and could improve it in the future. I have some test scripts that just detected the location of the file and used that as a reference point.

https://github.com/tl-its-umich-edu/api-utils-python/blob/5212d2a30664acb78b5b74c8a25296bced87f2a2/tests/test.py#L10

Comment by @jonespm

**Comment by jennlove-um** [comment]
Testing passes with this configuration set up.
