### ISSUE TITLE
Run core IPE process for applying competencies to students

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#7]
There are 5 IPE competencies and one dosage (course contact hours) that needs to be applied to each student in a assignment. Competencies/dosage are given based on 2 criteria
1. Shell roster
2. 70% grade  course. 

A assignment will be created with no submission, zero point, public and attaches with the IPE rubrics.

Rubrics will be created at IPE canvas subaccount and will grab the id. A rubrics once assigned cannot be changed. So it is same to us id instead of name 
IPE assignment Name : IPE Competencies Attained
IPE assignment group name: IPE competencies

API list for the process is described [here](https://docs.google.com/spreadsheets/d/1xFPSgvtrVz_wfH6qZjeIGBz7AjyCOF2uF-2a6QfAoME/edit?usp=sharing) 

The script workflow is described here

![ipe_process](https://user-images.githubusercontent.com/8579775/137396038-ea600be5-cfc8-4851-8a51-022e1dccc700.jpg)
 
**Child issues to close this:** 

1. #11 
2. https://github.com/tl-its-umich-edu/IPE-competencies-updater/issues/13
3. https://github.com/tl-its-umich-edu/IPE-competencies-updater/issues/14

**Comment by jennlove-um** [comment]
Testing passes - child issues tested successfully.
