### ISSUE TITLE
Run the script based on month entered in the google sheet

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#8]
The script will run 3 times a year, mostly one month after Fall/Winter/SpringSummer in Feb/June/Oct. 

Fall Term courses could be upto 15
Winter Term courses could be up to 10
Spring/Summer less than 5 

Based on the entry in the Google Spreedsheet columns (`When does script run? (Feb, June, Oct), Script Run?`) and the month configured in environmental variables `SCRIPT_RUN_MONTH` the script will pick courses to run.

```
if (When does script run? (Feb, June, Oct) == SCRIPT_RUN_MONTH & Script Run? == ''):
     pick the courses
else: don't pick up the courses
```

**Comment by jennlove-um** [comment]
Testing passes
