### ISSUE TITLE
Update the IPE spread sheet once ran the IPE process

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/IPE-competencies-updater#9]
The IPE team wants to know when the script ran. IPE spread sheet column "Script Run?" will be updated with current date

During analysis of the process, ran into Rate limiting process as `Google Sheets API has a limit of 500 requests per 100 seconds per project, and 100 requests per 100 seconds per user. Limits for reads and writes are tracked separately. 
There is no daily usage `
limit.https://developers.google.com/sheets/api/reference/limits

Rate limiting is seems to hit with less than  70 request. Need to keep this in mind when designing the approach

Solution: Updating the google sheet means we need to know exact row/column location of courseId and `Script Run?`. So that is read and write operation. So Reading the row/column of  `Script Run?`is one time thing but the courseId needs to be done for every courses. when we are iterating through courses for updating the competencies, we will update the google sheet one at a time since Bulk read is not possible. 

This way we avoid any rating limiting errors from Google sheets API since the whole process for assigning competencies will talk > ~1min. But in case we do hit this error, the code is pausing(sleeping) for 30 sec and retries 3 times before updating. This design make the google sheet update 100% always ( at-least this is good try to it)

**Comment by jennlove-um** [comment]
Testing passes.  No errors seen with updating the spreadsheet when running the script with multiple courses.
